import React, { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { Container, Button, Table, Spinner, Card } from "react-bootstrap";
import { PDFDownloadLink, Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer';
import { getMockTestBySubject, getResultAnalysis } from "../../Services/mockTestService";
import ResultSummary from "../../components/MockTest/ResultSummary";
import ResultCharts from "../../components/MockTest/ResultCharts";
import { Download, LibraryBooks, RestartAlt } from "@mui/icons-material";
import { toast } from "react-toastify";

// PDF Styles
const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 12, fontFamily: 'Helvetica' },
  title: { fontSize: 24, marginBottom: 10, textAlign: 'center', color: '#0d6efd' },
  subtitle: { fontSize: 16, marginBottom: 20, textAlign: 'center', color: '#6c757d' },
  section: { marginBottom: 20, borderBottom: '1px solid #eee', paddingBottom: 10 },
  heading: { fontWeight: 'bold', marginBottom: 10, fontSize: 14 },
  row: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 5 },
  label: { color: '#444' },
  value: { fontWeight: 'bold' }
});

const ResultPDF = ({ test, results, studentName }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <Text style={styles.title}>All-Score-100 Performance Report</Text>
      <Text style={styles.subtitle}>{test.title}</Text>
      <View style={styles.section}>
        <Text style={styles.heading}>Student Summary</Text>
        <View style={styles.row}><Text style={styles.label}>Student Name</Text><Text style={styles.value}>{studentName}</Text></View>
        <View style={styles.row}><Text style={styles.label}>Total Questions</Text><Text style={styles.value}>{results.total}</Text></View>
        <View style={styles.row}><Text style={styles.label}>Attempted</Text><Text style={styles.value}>{results.attempted}</Text></View>
        <View style={styles.row}><Text style={styles.label}>Correct</Text><Text style={styles.value}>{results.correct}</Text></View>
        <View style={styles.row}><Text style={styles.label}>Wrong</Text><Text style={styles.value}>{results.wrong}</Text></View>
        <View style={styles.row}><Text style={styles.label}>Score</Text><Text style={styles.value}>{results.score}</Text></View>
        <View style={styles.row}><Text style={styles.label}>Percentage</Text><Text style={styles.value}>{results.percentage}%</Text></View>
      </View>
      <Text style={{ textAlign: 'center', color: '#888', marginTop: 50, fontSize: 10 }}>Generated by All-Score-100 System</Text>
    </Page>
  </Document>
);

const ResultPage = () => {
  const { testId, attemptId } = useParams();
  const navigate = useNavigate();
  const [test, setTest] = useState(null);
  const [results, setResults] = useState(null);
  const [loading, setLoading] = useState(true);
  const [user, setUser] = useState(null);

  useEffect(() => {
    const savedUser = localStorage.getItem("user");
    if (savedUser) {
      try {
        setUser(JSON.parse(savedUser));
      } catch (e) {
        console.error("Failed to parse user from localStorage", e);
      }
    }
  }, []);

  useEffect(() => {
    const loadFullResults = async () => {
      try {
        const [testData, resultData] = await Promise.all([
          getMockTestBySubject(testId),
          getResultAnalysis(attemptId)
        ]);

        setTest(testData);
        
        // Map backend fields to UI model
        setResults({
          total: resultData.totalQuestions || resultData.correctAnswers + resultData.wrongAnswers + resultData.skippedQuestions,
          correct: resultData.correctAnswers || resultData.correct,
          wrong: resultData.wrongAnswers || resultData.wrong,
          skipped: resultData.skippedQuestions || resultData.skipped,
          attempted: (resultData.correctAnswers || resultData.correct) + (resultData.wrongAnswers || resultData.wrong),
          score: resultData.score,
          percentage: resultData.percentage,
          accuracy: resultData.correctAnswers + resultData.wrongAnswers > 0 
            ? ((resultData.correctAnswers / (resultData.correctAnswers + resultData.wrongAnswers)) * 100).toFixed(2) 
            : 0
        });
      } catch (err) {
        console.error("Error loading results:", err);
        toast.error("Failed to load investigation results.");
      } finally {
        setLoading(false);
      }
    };

    if (testId && attemptId) {
      loadFullResults();
    }
  }, [testId, attemptId]);

  const studentName = user?.userName || "Student";

  if (loading) return <div className="vh-100 d-flex align-items-center justify-content-center flex-column">
     <Spinner animation="border" variant="primary" className="mb-3" />
     <p className="text-muted fw-bold">Analyzing Results...</p>
  </div>;
  
  if (!results) return <div className="text-center mt-5">Result record not found for Attempt ID: {attemptId}</div>;

  return (
    <div className="bg-light min-vh-100 py-5">
      <Container>
        <div className="d-flex flex-column flex-md-row justify-content-between align-items-md-end mb-5 gap-3">
          <div>
            <h1 className="fw-bold mb-2">Examination Report</h1>
            <h5 className="text-muted mb-1">{test?.title || "Exam Results"}</h5>
            <div className="text-muted mb-2">Student Name: <strong className="text-dark">{studentName}</strong></div>
            <small className="text-primary fw-bold">Attempt ID: {attemptId}</small>
          </div>
          <div className="d-flex gap-2">
            <PDFDownloadLink 
              document={<ResultPDF test={test} results={results} studentName={studentName} />} 
              fileName={`Result_${testId}_${attemptId}.pdf`}
              className="btn btn-primary shadow-sm"
            >
              {({ loading }) => (
                loading ? 'Preparing...' : <><Download className="me-2" /> Download PDF</>
              )}
            </PDFDownloadLink>
            <Button variant="outline-primary" className="shadow-sm" onClick={() => navigate(`/mock-test/${testId}/start`)}>
              <RestartAlt className="me-2" /> Retake
            </Button>
          </div>
        </div>

        <ResultSummary results={results} />
        <ResultCharts results={results} />

        <div className="d-grid mt-4">
           <Button variant="dark" size="lg" className="fw-bold py-3 shadow-sm" onClick={() => navigate(`/mock-test/${testId}/solutions`)}>
              <LibraryBooks className="me-2" /> View Detailed Solutions & Explanations
           </Button>
        </div>
      </Container>
    </div>
  );
};

export default ResultPage;
